[tool.poetry]
name = "drumpy-analysis"
version = "0.1.0"
description = ""
authors = ["Maurice Van Wassenhove <mauricevanwassenhove@fastmail.com>"]
packages = [{ include = "drumpy_analysis" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "~3.11"
qtm-rt = "3.0.1"
bokeh = "3.3.4"
drumpy = {path = "DrumPy"}
matplotlib = "3.8.3"
scipy = "^1.12.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.1"
deptry = "0.12.0"
