[tool.poetry]
name = "drumpy-analysis"
version = "0.1.0"
description = ""
authors = ["Maurice Van Wassenhove <mauricevanwassenhove@fastmail.com>"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "~3.11"
qtm-rt = "3.0.1"
bokeh = "3.3.4"
matplotlib = "3.8.3"
scipy = "^1.12.0"
line-profiler-pycharm = "^1.1.0"
mpld3 = "^0.5.10"
drumpy = {path = "DrumPy", develop = true}


[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.2"
deptry = "0.14.2"
